ALTER TABLE account ADD COLUMN IF NOT EXISTS balance BIGINT NOT NULL DEFAULT 0;
ALTER TABLE account ADD COLUMN version BIGINT NOT NULL DEFAULT 0;

ALTER TABLE transfer ADD COLUMN timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;